default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: 'inclub'
  username: 'root'
  password: ''

test:
  <<: *default
  database: 'inclub_test'
  username: 'root'
  password: ''

production:
  <<: *default
  database: 'inclub'
  username: 'root'
  password: "ach20252017"
  host: 35.184.66.35
  port: 3306


# @connection = ActiveRecord::Base.establish_connection(
#   adapter: 'mysql2',
#   encoding: 'utf8',
#   pool: 5,
#   timeout: 5000,
#   username: 'root',
#   password: "ach20252017",
#   host: '35.184.66.35',
#   port: 3306,
#   database: 'inclub')
