require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FestaController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Festum. As you add validations to Festum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FestaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all festa as @festa" do
      festum = Festum.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:festa)).to eq([festum])
    end
  end

  describe "GET #show" do
    it "assigns the requested festum as @festum" do
      festum = Festum.create! valid_attributes
      get :show, params: {id: festum.to_param}, session: valid_session
      expect(assigns(:festum)).to eq(festum)
    end
  end

  describe "GET #new" do
    it "assigns a new festum as @festum" do
      get :new, params: {}, session: valid_session
      expect(assigns(:festum)).to be_a_new(Festum)
    end
  end

  describe "GET #edit" do
    it "assigns the requested festum as @festum" do
      festum = Festum.create! valid_attributes
      get :edit, params: {id: festum.to_param}, session: valid_session
      expect(assigns(:festum)).to eq(festum)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Festum" do
        expect {
          post :create, params: {festum: valid_attributes}, session: valid_session
        }.to change(Festum, :count).by(1)
      end

      it "assigns a newly created festum as @festum" do
        post :create, params: {festum: valid_attributes}, session: valid_session
        expect(assigns(:festum)).to be_a(Festum)
        expect(assigns(:festum)).to be_persisted
      end

      it "redirects to the created festum" do
        post :create, params: {festum: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Festum.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved festum as @festum" do
        post :create, params: {festum: invalid_attributes}, session: valid_session
        expect(assigns(:festum)).to be_a_new(Festum)
      end

      it "re-renders the 'new' template" do
        post :create, params: {festum: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested festum" do
        festum = Festum.create! valid_attributes
        put :update, params: {id: festum.to_param, festum: new_attributes}, session: valid_session
        festum.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested festum as @festum" do
        festum = Festum.create! valid_attributes
        put :update, params: {id: festum.to_param, festum: valid_attributes}, session: valid_session
        expect(assigns(:festum)).to eq(festum)
      end

      it "redirects to the festum" do
        festum = Festum.create! valid_attributes
        put :update, params: {id: festum.to_param, festum: valid_attributes}, session: valid_session
        expect(response).to redirect_to(festum)
      end
    end

    context "with invalid params" do
      it "assigns the festum as @festum" do
        festum = Festum.create! valid_attributes
        put :update, params: {id: festum.to_param, festum: invalid_attributes}, session: valid_session
        expect(assigns(:festum)).to eq(festum)
      end

      it "re-renders the 'edit' template" do
        festum = Festum.create! valid_attributes
        put :update, params: {id: festum.to_param, festum: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested festum" do
      festum = Festum.create! valid_attributes
      expect {
        delete :destroy, params: {id: festum.to_param}, session: valid_session
      }.to change(Festum, :count).by(-1)
    end

    it "redirects to the festa list" do
      festum = Festum.create! valid_attributes
      delete :destroy, params: {id: festum.to_param}, session: valid_session
      expect(response).to redirect_to(festa_url)
    end
  end

end
